version: "3.7"

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql://postgres:toluwanimi@host.docker.internal:5000/cakeShop
    volumes:
      - .:/app
    ports:
      - 8000:8000

volumes:
  cake_shop_db: